title: h
author: netsuke
email: none of your business :D
description: > # this means to ignore newlines until "baseurl:"
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAurmumAAAAA

# social links
twitter_username: netsu
github_username:  nettopet

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
